# Generated by Django 2.1.2 on 2019-01-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nascimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15)),
                ('pai', models.CharField(max_length=255)),
                ('mae', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='fotos')),
            ],
        ),
    ]
