# Generated by Django 2.1.2 on 2019-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nascimento',
            name='imagem',
            field=models.ImageField(upload_to='media'),
        ),
    ]
