# Generated by Django 2.1.2 on 2019-01-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190128_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marido', models.CharField(max_length=255)),
                ('mulher', models.CharField(max_length=255)),
                ('cpf_marido', models.CharField(max_length=15)),
                ('cpf_mulher', models.CharField(max_length=15)),
                ('imagem', models.ImageField(upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Divorcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marido', models.CharField(max_length=255)),
                ('mulher', models.CharField(max_length=255)),
                ('cpf_marido', models.CharField(max_length=15)),
                ('cpf_mulher', models.CharField(max_length=15)),
                ('imagem', models.ImageField(upload_to='fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Natimorto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=15)),
                ('pai', models.CharField(max_length=255)),
                ('mae', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='fotos')),
            ],
        ),
    ]
