# Generated by Django 2.2 on 2019-04-18 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_nascimento_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='nascimento',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Livro'),
            preserve_default=False,
        ),
    ]
